# Generated by Django 5.2.5 on 2025-08-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('role', models.CharField(choices=[('student_teacher', 'Student Teacher'), ('teacher', 'Teacher'), ('department_head', 'Department Head')], max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('affiliations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('due_soon', 'Due Soon'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('new', 'New Task')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.user'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10)),
                ('time', models.CharField(choices=[('8:00 - 9:00 AM', '8:00 - 9:00 AM'), ('9:00 - 10:00 AM', '9:00 - 10:00 AM'), ('10:00 - 11:00 AM', '10:00 - 11:00 AM'), ('11:00 - 12:00 PM', '11:00 - 12:00 PM'), ('1:00 - 2:00 PM', '1:00 - 2:00 PM'), ('2:00 - 3:00 PM', '2:00 - 3:00 PM'), ('3:00 - 4:00 PM', '3:00 - 4:00 PM'), ('4:00 - 5:00 PM', '4:00 - 5:00 PM')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.user')),
            ],
            options={
                'unique_together': {('user', 'day', 'time')},
            },
        ),
    ]
