# Generated by Django 5.2.5 on 2025-08-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture for the user', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student Teacher', 'Student Teacher'), ('Teacher', 'Teacher'), ('Department Head', 'Department Head')], max_length=100),
        ),
    ]
