# Generated by Django 5.2.5 on 2025-09-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_user_profile_picture_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_id', models.CharField(max_length=50, unique=True)),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('province', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook_page', models.URLField(blank=True, null=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('agreed_terms', models.BooleanField(default=False)),
                ('agreed_accuracy', models.BooleanField(default=False)),
                ('agreed_communications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
