# Generated by Django 5.1.2 on 2025-08-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_user_affiliations_alter_user_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='e.g. Mathematics, English, Science', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the class', null=True)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], help_text='Day of the week for the class', max_length=10)),
                ('time', models.CharField(choices=[('8:00 - 9:00 AM', '8:00 - 9:00 AM'), ('9:00 - 10:00 AM', '9:00 - 10:00 AM'), ('10:00 - 11:00 AM', '10:00 - 11:00 AM'), ('11:00 - 12:00 PM', '11:00 - 12:00 PM'), ('1:00 - 2:00 PM', '1:00 - 2:00 PM'), ('2:00 - 3:00 PM', '2:00 - 3:00 PM'), ('3:00 - 4:00 PM', '3:00 - 4:00 PM'), ('4:00 - 5:00 PM', '4:00 - 5:00 PM')], help_text='Time slot for the class', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class Schedule',
                'verbose_name_plural': 'Class Schedules',
                'ordering': ['day', 'time'],
            },
        ),
    ]
