# Generated by Django 5.2.5 on 2025-09-08 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_schoolregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'School Registration', 'verbose_name_plural': 'School Registrations'},
        ),
        migrations.RemoveField(
            model_name='schoolregistration',
            name='agreed_accuracy',
        ),
        migrations.RemoveField(
            model_name='schoolregistration',
            name='agreed_communications',
        ),
        migrations.RemoveField(
            model_name='schoolregistration',
            name='agreed_terms',
        ),
        migrations.RemoveField(
            model_name='schoolregistration',
            name='phone',
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='accuracy',
            field=models.BooleanField(default=False, help_text='Certifies that all information provided is accurate and complete', verbose_name='Information Accuracy Certification'),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for administrators', null=True, verbose_name='Admin Notes'),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='communications',
            field=models.BooleanField(default=False, help_text='Consent to receive updates about platform features via email', verbose_name='Communications Consent'),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='phone_number',
            field=models.CharField(default='N/A', help_text='Main contact phone number', max_length=20, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Date when the registration was processed', null=True, verbose_name='Processing Date'),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who processed this registration', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lesson.user', verbose_name='Processed By'),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs Additional Information')], default='pending', max_length=20, verbose_name='Registration Status'),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='terms',
            field=models.BooleanField(default=False, help_text='Agreement to Terms of Service and Privacy Policy', verbose_name='Terms and Privacy Agreement'),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='address',
            field=models.TextField(help_text='Street, Barangay, City/Municipality', verbose_name='Complete Address'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload school registration certificate or similar document', null=True, upload_to='school_certificates/', verbose_name='School Certificate'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='contact_email',
            field=models.EmailField(help_text='Email address of the contact person', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='contact_person',
            field=models.CharField(help_text='Primary contact person for system administration', max_length=255, verbose_name='Contact Person Name'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='contact_phone',
            field=models.CharField(help_text='Phone number of the contact person', max_length=20, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='email',
            field=models.EmailField(help_text='Official school email address', max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='facebook_page',
            field=models.URLField(blank=True, help_text="School's official Facebook page", null=True, verbose_name='Facebook Page'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='position',
            field=models.CharField(help_text='Job title of the contact person', max_length=100, verbose_name='Position/Title'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='province',
            field=models.CharField(max_length=100, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='region',
            field=models.CharField(choices=[('Region IX - Zamboanga Peninsula', 'Region IX - Zamboanga Peninsula'), ('BARMM', 'BARMM'), ('NCR', 'National Capital Region'), ('CAR', 'Cordillera Administrative Region'), ('Region I - Ilocos Region', 'Region I - Ilocos Region'), ('Region II - Cagayan Valley', 'Region II - Cagayan Valley'), ('Region III - Central Luzon', 'Region III - Central Luzon'), ('Region IV-A - CALABARZON', 'Region IV-A - CALABARZON'), ('Region IV-B - MIMAROPA', 'Region IV-B - MIMAROPA'), ('Region V - Bicol Region', 'Region V - Bicol Region'), ('Region VI - Western Visayas', 'Region VI - Western Visayas'), ('Region VII - Central Visayas', 'Region VII - Central Visayas'), ('Region VIII - Eastern Visayas', 'Region VIII - Eastern Visayas'), ('Region X - Northern Mindanao', 'Region X - Northern Mindanao'), ('Region XI - Davao Region', 'Region XI - Davao Region'), ('Region XII - SOCCSKSARGEN', 'Region XII - SOCCSKSARGEN'), ('Region XIII - Caraga', 'Region XIII - Caraga')], max_length=100, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='school_id',
            field=models.CharField(help_text='12-digit DepEd registration code or school identifier', max_length=50, unique=True, verbose_name='School ID / DepEd Code'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='school_name',
            field=models.CharField(help_text='Complete official name of the institution', max_length=255, verbose_name='Official School Name'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='website',
            field=models.URLField(blank=True, help_text="School's official website", null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='year_established',
            field=models.PositiveIntegerField(blank=True, help_text='Year the institution was established', null=True, verbose_name='Year Established'),
        ),
        migrations.AddIndex(
            model_name='schoolregistration',
            index=models.Index(fields=['status'], name='lesson_scho_status_a50d94_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolregistration',
            index=models.Index(fields=['created_at'], name='lesson_scho_created_910118_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolregistration',
            index=models.Index(fields=['school_id'], name='lesson_scho_school__cafec3_idx'),
        ),
    ]
