# Generated by Django 5.2.5 on 2025-08-23 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_classschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10)),
                ('time', models.CharField(choices=[('8:00 - 9:00 AM', '8:00 - 9:00 AM'), ('9:00 - 10:00 AM', '9:00 - 10:00 AM'), ('10:00 - 11:00 AM', '10:00 - 11:00 AM'), ('11:00 - 12:00 PM', '11:00 - 12:00 PM'), ('1:00 - 2:00 PM', '1:00 - 2:00 PM'), ('2:00 - 3:00 PM', '2:00 - 3:00 PM'), ('3:00 - 4:00 PM', '3:00 - 4:00 PM'), ('4:00 - 5:00 PM', '4:00 - 5:00 PM')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.user')),
            ],
            options={
                'unique_together': {('user', 'day', 'time')},
            },
        ),
        migrations.DeleteModel(
            name='ClassSchedule',
        ),
    ]
