# Generated by Django 5.2.5 on 2025-08-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_schedule_delete_classschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student_teacher', 'Student Teacher'), ('teacher', 'Teacher'), ('department_head', 'Department Head')], max_length=100),
        ),
    ]
