# Generated by Django 5.2.5 on 2025-09-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_alter_schoolregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
