# Generated by Django 5.2.5 on 2025-09-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_lessonplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonPlan',
        ),
    ]
