# Generated by Django 5.1 on 2025-09-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
