# Generated by Django 5.1 on 2025-09-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolregistration',
            name='certificate_file',
        ),
    ]
