# Generated by Django 5.1.2 on 2025-09-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0012_lessonplansubmission'),
        ('lessonGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lessonplansubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['submitted', 'approved', 'needs_revision'])), fields=('lesson_plan', 'status'), name='unique_active_submission'),
        ),
    ]
