# Generated by Django 5.1 on 2025-10-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0013_lessonplansubmission_unique_active_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolregistration',
            name='password',
            field=models.CharField(blank=True, help_text='Password for the school administrator account', max_length=128, null=True, verbose_name='Admin Password'),
        ),
    ]
