# Generated by Django 5.2.5 on 2025-10-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0014_schoolregistration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolregistration',
            name='year_established',
            field=models.PositiveIntegerField(default=2024, help_text='Year the institution was established', verbose_name='Year Established'),
            preserve_default=False,
        ),
    ]
