# Generated by Django 5.2.5 on 2025-10-16 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0016_alter_user_role_adminlog_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_modified', 'User Modified'), ('user_deactivated', 'User Deactivated'), ('role_changed', 'Role Changed'), ('lesson_approved', 'Lesson Approved'), ('lesson_flagged', 'Lesson Flagged'), ('password_reset', 'Password Reset'), ('account_unlocked', 'Account Unlocked'), ('school_admin_created', 'School Admin Created'), ('school_admin_deactivated', 'School Admin Deactivated'), ('school_admin_activated', 'School Admin Activated')], max_length=50),
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_school_admins', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='lesson.schoolregistration')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Admin',
                'verbose_name_plural': 'School Admins',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'is_active'], name='lesson_scho_school__22319c_idx'), models.Index(fields=['created_at'], name='lesson_scho_created_e6d94b_idx')],
            },
        ),
    ]
