# Generated by Django 5.2.5 on 2025-11-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0018_exemplar'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplar',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
