# Generated by Django 5.2.5 on 2025-11-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0021_user_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Explanation provided to student when account was disapproved', null=True, verbose_name='Reason for Rejection'),
        ),
    ]
