# Generated by Django 5.2.5 on 2026-01-23 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0023_studentconcern'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('registration_received', 'Registration Received'), ('registration_approved', 'Registration Approved'), ('registration_rejected', 'Registration Rejected'), ('additional_info_requested', 'Additional Information Requested'), ('welcome_school_admin', 'Welcome School Admin')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Use {{school_name}}, {{contact_person}}, etc. as variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(choices=[('NCR - National Capital Region', 'NCR - National Capital Region'), ('Region I - Ilocos Region', 'Region I - Ilocos Region'), ('Region II - Cagayan Valley', 'Region II - Cagayan Valley'), ('Region III - Central Luzon', 'Region III - Central Luzon'), ('Region IV-A - CALABARZON', 'Region IV-A - CALABARZON'), ('Region IV-B - MIMAROPA', 'Region IV-B - MIMAROPA'), ('Region V - Bicol Region', 'Region V - Bicol Region'), ('Region VI - Western Visayas', 'Region VI - Western Visayas'), ('Region VII - Central Visayas', 'Region VII - Central Visayas'), ('Region VIII - Eastern Visayas', 'Region VIII - Eastern Visayas'), ('Region IX - Zamboanga Peninsula', 'Region IX - Zamboanga Peninsula'), ('Region X - Northern Mindanao', 'Region X - Northern Mindanao'), ('Region XI - Davao Region', 'Region XI - Davao Region'), ('Region XII - SOCCSKSARGEN', 'Region XII - SOCCSKSARGEN'), ('Region XIII - Caraga', 'Region XIII - Caraga'), ('BARMM - Bangsamoro Autonomous Region in Muslim Mindanao', 'BARMM - Bangsamoro Autonomous Region in Muslim Mindanao'), ('CAR - Cordillera Administrative Region', 'CAR - Cordillera Administrative Region')], max_length=100)),
                ('region_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='schoolregistration',
            name='password',
        ),
        migrations.AddField(
            model_name='adminlog',
            name='target_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lesson.schoolregistration'),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='logo_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Original Logo Filename'),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='password_hash',
            field=models.CharField(blank=True, help_text='Hashed password for the school administrator account', max_length=128, null=True, verbose_name='Password Hash'),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='school_logo',
            field=models.ImageField(blank=True, help_text='Recommended: Square logo, JPG/PNG, max 2MB', null=True, upload_to='school_logos/', verbose_name='School Logo'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_modified', 'User Modified'), ('user_deactivated', 'User Deactivated'), ('role_changed', 'Role Changed'), ('lesson_approved', 'Lesson Approved'), ('lesson_flagged', 'Lesson Flagged'), ('password_reset', 'Password Reset'), ('account_unlocked', 'Account Unlocked'), ('school_admin_created', 'School Admin Created'), ('school_admin_deactivated', 'School Admin Deactivated'), ('school_admin_activated', 'School Admin Activated'), ('school_registered', 'School Registration Submitted'), ('school_approved', 'School Registration Approved'), ('school_rejected', 'School Registration Rejected'), ('school_info_requested', 'School Additional Info Requested')], max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='region',
            field=models.CharField(choices=[('NCR - National Capital Region', 'NCR - National Capital Region'), ('Region I - Ilocos Region', 'Region I - Ilocos Region'), ('Region II - Cagayan Valley', 'Region II - Cagayan Valley'), ('Region III - Central Luzon', 'Region III - Central Luzon'), ('Region IV-A - CALABARZON', 'Region IV-A - CALABARZON'), ('Region IV-B - MIMAROPA', 'Region IV-B - MIMAROPA'), ('Region V - Bicol Region', 'Region V - Bicol Region'), ('Region VI - Western Visayas', 'Region VI - Western Visayas'), ('Region VII - Central Visayas', 'Region VII - Central Visayas'), ('Region VIII - Eastern Visayas', 'Region VIII - Eastern Visayas'), ('Region IX - Zamboanga Peninsula', 'Region IX - Zamboanga Peninsula'), ('Region X - Northern Mindanao', 'Region X - Northern Mindanao'), ('Region XI - Davao Region', 'Region XI - Davao Region'), ('Region XII - SOCCSKSARGEN', 'Region XII - SOCCSKSARGEN'), ('Region XIII - Caraga', 'Region XIII - Caraga'), ('BARMM - Bangsamoro Autonomous Region in Muslim Mindanao', 'BARMM - Bangsamoro Autonomous Region in Muslim Mindanao'), ('CAR - Cordillera Administrative Region', 'CAR - Cordillera Administrative Region')], max_length=100, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='year_established',
            field=models.PositiveIntegerField(blank=True, help_text='Year the institution was established', null=True, verbose_name='Year Established'),
        ),
        migrations.AddIndex(
            model_name='schoolregistration',
            index=models.Index(fields=['region'], name='lesson_scho_region_21da52_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolregistration',
            index=models.Index(fields=['contact_email'], name='lesson_scho_contact_9289d4_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['region'], name='lesson_prov_region_b334e9_idx'),
        ),
    ]
