# Generated by Django 5.2.8 on 2026-02-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0026_add_schedule_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='instructor',
            field=models.CharField(default='Instructor', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(default='New Class', max_length=200),
        ),
    ]
