# Generated by Django 5.2.5 on 2026-03-06 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0027_alter_schedule_day_alter_schedule_instructor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('task_due_soon', 'Task Due Soon'), ('task_overdue', 'Task Overdue'), ('task_completed', 'Task Completed'), ('task_created', 'Task Created'), ('lesson_submitted', 'Lesson Submitted'), ('lesson_approved', 'Lesson Approved'), ('lesson_rejected', 'Lesson Rejected'), ('lesson_needs_revision', 'Lesson Needs Revision'), ('student_concern', 'Student Concern'), ('concern_resolved', 'Concern Resolved'), ('schedule_reminder', 'Schedule Reminder'), ('general', 'General')], default='general', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('lesson_plan_id', models.IntegerField(blank=True, null=True)),
                ('submission_id', models.IntegerField(blank=True, null=True)),
                ('concern_id', models.IntegerField(blank=True, null=True)),
                ('schedule_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='lesson_noti_user_id_aa6c7f_idx'), models.Index(fields=['user', 'is_read'], name='lesson_noti_user_id_44f6d4_idx')],
            },
        ),
    ]
