# Generated by Django 5.2.5 on 2026-03-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0028_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_due_soon', 'Task Due Soon'), ('task_due_1hour', 'Task Due in 1 Hour'), ('task_overdue', 'Task Overdue'), ('task_completed', 'Task Completed'), ('task_created', 'Task Created'), ('lesson_submitted', 'Lesson Submitted'), ('lesson_approved', 'Lesson Approved'), ('lesson_rejected', 'Lesson Rejected'), ('lesson_needs_revision', 'Lesson Needs Revision'), ('student_concern', 'Student Concern'), ('concern_resolved', 'Concern Resolved'), ('schedule_reminder', 'Schedule Reminder'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
