# Generated by Django 5.2.5 on 2026-03-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0029_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, help_text='ID of the related object (e.g., weekly plan ID)', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_type',
            field=models.CharField(blank=True, help_text="Type of related object (e.g., 'weekly_lesson_plan')", max_length=50, null=True),
        ),
    ]
