# Generated by Django 5.2.5 on 2025-09-23 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonlinkCalendar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendaractivity',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='calendaractivity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendaractivity',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
