# Generated by Django 5.2.5 on 2025-10-02 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0015_alter_schoolregistration_year_established'),
        ('lessonlinkCalendar', '0002_remove_calendaractivity_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendaractivity',
            options={'ordering': ['start_date', 'title'], 'verbose_name_plural': 'Calendar Activities'},
        ),
        migrations.AddField(
            model_name='calendaractivity',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calendaractivity',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.schoolregistration'),
        ),
        migrations.AddField(
            model_name='calendaractivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calendaractivity',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('examination', 'Examination'), ('holiday', 'Holiday'), ('meeting', 'Meeting'), ('event', 'Event'), ('deadline', 'Deadline'), ('training', 'Training'), ('enrollment', 'Enrollment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='calendaractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
