# Generated by Django 5.2.5 on 2025-10-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonlinkCalendar', '0003_alter_calendaractivity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZamboangaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_month', models.PositiveIntegerField(help_text='Month (1-12)')),
                ('start_day', models.PositiveIntegerField(help_text='Day of month (1-31)')),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='How many days the event lasts')),
                ('category', models.CharField(choices=[('festival', 'Festival'), ('cultural', 'Cultural'), ('holiday', 'Holiday'), ('sports', 'Sports'), ('government', 'Government'), ('religious', 'Religious')], max_length=20)),
                ('location', models.CharField(default='Zamboanga City', max_length=300)),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('is_annual', models.BooleanField(default=True, help_text='Event repeats every year automatically')),
                ('is_active', models.BooleanField(default=True, help_text='Show this event in the calendar')),
                ('notes', models.TextField(blank=True, help_text='Additional information about the event')),
            ],
            options={
                'verbose_name_plural': 'Zamboanga Events',
                'ordering': ['start_month', 'start_day'],
            },
        ),
    ]
