# Generated by Django 5.2.5 on 2025-09-14 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('grade_level', models.CharField(max_length=50)),
                ('quarter', models.CharField(blank=True, max_length=50)),
                ('duration', models.IntegerField()),
                ('population', models.IntegerField()),
                ('learning_objectives', models.TextField()),
                ('subject_matter', models.TextField()),
                ('materials_needed', models.TextField()),
                ('introduction', models.TextField()),
                ('instruction', models.TextField()),
                ('application', models.TextField()),
                ('evaluation', models.TextField()),
                ('assessment', models.TextField()),
                ('generated_content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
