# Generated by Django 5.1.2 on 2025-09-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='auto_approved',
            field=models.BooleanField(default=False, help_text='Automatically approved for department heads'),
        ),
    ]
