# Generated by Django 5.1.2 on 2025-10-27 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonGenerator', '0002_lessonplan_auto_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='content_standard',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='cross_curricular',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='learning_competency',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='melc_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='performance_standard',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='values_integration',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='population',
            field=models.IntegerField(help_text='Number of students'),
        ),
        migrations.CreateModel(
            name='LessonPlanSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lessonGenerator.lessonplan')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_plans', to=settings.AUTH_USER_MODEL)),
                ('submitted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
    ]
