# Generated by Django 5.2.5 on 2025-12-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonGenerator', '0003_lessonplan_content_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='intelligence_type',
            field=models.CharField(choices=[('comprehensive', 'Comprehensive (IQ+EQ+SQ+AQ)'), ('cognitive', 'Cognitive Focus (IQ) - Logical & Analytical'), ('emotional', 'Emotional Focus (EQ) - Self & Social Awareness'), ('social', 'Social Focus (SQ) - Collaboration & Communication'), ('resilience', 'Resilience Focus (AQ) - Perseverance & Adaptability'), ('differentiated', 'Differentiated Mix - All Types with Varied Activities')], default='comprehensive', help_text='Type of intelligence to focus lesson plan adaptation on', max_length=20),
        ),
    ]
