# Generated by Django 5.2.5 on 2026-03-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonGenerator', '0006_weeklylessonplan_review_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('final', 'Final')], default='draft', max_length=10),
        ),
    ]
