# Generated by Django 5.2.5 on 2026-03-15 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonGenerator', '0007_alter_lessonplan_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyLessonPlanSubmission',
        ),
    ]
