# Generated by Django 5.2.5 on 2026-03-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonGenerator', '0008_delete_weeklylessonplansubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylessonplan',
            name='friday_procedure_a_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/friday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='friday_procedure_b_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/friday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='friday_procedure_c_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/friday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='friday_procedure_d_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/friday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='friday_procedure_e_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/friday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='friday_procedure_f_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/friday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='friday_procedure_g_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/friday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='friday_procedure_h_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/friday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='friday_procedure_i_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/friday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='friday_procedure_j_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/friday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='monday_procedure_a_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/monday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='monday_procedure_b_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/monday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='monday_procedure_c_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/monday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='monday_procedure_d_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/monday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='monday_procedure_e_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/monday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='monday_procedure_f_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/monday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='monday_procedure_g_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/monday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='monday_procedure_h_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/monday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='monday_procedure_i_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/monday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='monday_procedure_j_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/monday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='thursday_procedure_a_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/thursday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='thursday_procedure_b_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/thursday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='thursday_procedure_c_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/thursday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='thursday_procedure_d_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/thursday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='thursday_procedure_e_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/thursday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='thursday_procedure_f_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/thursday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='thursday_procedure_g_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/thursday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='thursday_procedure_h_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/thursday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='thursday_procedure_i_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/thursday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='thursday_procedure_j_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/thursday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='tuesday_procedure_a_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/tuesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='tuesday_procedure_b_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/tuesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='tuesday_procedure_c_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/tuesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='tuesday_procedure_d_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/tuesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='tuesday_procedure_e_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/tuesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='tuesday_procedure_f_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/tuesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='tuesday_procedure_g_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/tuesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='tuesday_procedure_h_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/tuesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='tuesday_procedure_i_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/tuesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='tuesday_procedure_j_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/tuesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='wednesday_procedure_a_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/wednesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='wednesday_procedure_b_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/wednesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='wednesday_procedure_c_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/wednesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='wednesday_procedure_d_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/wednesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='wednesday_procedure_e_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/wednesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='wednesday_procedure_f_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/wednesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='wednesday_procedure_g_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/wednesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='wednesday_procedure_h_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/wednesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='wednesday_procedure_i_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/wednesday/'),
        ),
        migrations.AddField(
            model_name='weeklylessonplan',
            name='wednesday_procedure_j_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_procedures/wednesday/'),
        ),
    ]
