# Generated by Django 5.2.5 on 2026-03-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonGenerator', '0009_weeklylessonplan_friday_procedure_a_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='application_image',
            field=models.ImageField(blank=True, null=True, upload_to='daily_procedures/application/'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='assessment_image',
            field=models.ImageField(blank=True, null=True, upload_to='daily_procedures/assessment/'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='evaluation_image',
            field=models.ImageField(blank=True, null=True, upload_to='daily_procedures/evaluation/'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='instruction_image',
            field=models.ImageField(blank=True, null=True, upload_to='daily_procedures/instruction/'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='introduction_image',
            field=models.ImageField(blank=True, null=True, upload_to='daily_procedures/introduction/'),
        ),
    ]
