# Generated by Django 5.2.5 on 2026-03-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonGenerator', '0010_lessonplan_application_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProcedureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10)),
                ('step', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G'), ('h', 'H'), ('i', 'I'), ('j', 'J')], max_length=1)),
                ('image', models.ImageField(upload_to='weekly_procedures/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_images', to='lessonGenerator.weeklylessonplan')),
            ],
            options={
                'ordering': ['day', 'step', 'order'],
            },
        ),
    ]
