# Generated by Django 5.2.5 on 2026-03-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonGenerator', '0011_weeklyprocedureimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('introduction', 'Introduction'), ('instruction', 'Instruction'), ('application', 'Application'), ('evaluation', 'Evaluation'), ('assessment', 'Assessment')], max_length=20)),
                ('image', models.ImageField(upload_to='daily_plan_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lessonGenerator.lessonplan')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
    ]
